auction/urls.py
from django.urls import path
from.import views

urlpatterns = [
    path('',views.home,name="home"),
    path('bidnow',views.bidnow,name="bidnow"),
    path('onsale',views.onsale,name="onsale"),
    path('contact',views.contact,name="contact"),
    path('about',views.about,name="about"),
    path('tsandcs',views.tsandcs,name="tsandcs"),
    path('login/', views.login_process,name='login'),
    path('logout/', views.logout_process,name='logout'),
    path('faqs',views.faqs,name="faqs"),
    path('bidders',views.bidders,name="bidders"),
    path('product/<int:id>/',views.product, name="product"),
    path('product/<int:id>/make_bid',views.make_bid, name="make_bid"),
]

bgmainapp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.urls.conf import re_path
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('auction.urls')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),
]

auction/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Auction_details(models.Model):
    start_date = models.DateField(editable=True)
    end_time = models.DurationField()
    auction_on = models.BooleanField(default=False)

class Registration(models.Model):
    first_name = models.CharField(max_length=100)
    last_name  = models.CharField(max_length=100)
    phone  = models.CharField(max_length=100)

    def __str__(self):
        return self.first_name
    

class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Bidder(User):
 
    def __str__(self):
        return self.first_name

class Product(models.Model):
    product_name = models.CharField(max_length=200)
    product_description = models.TextField(max_length=1000)
    product_thumbnail = models.ImageField()
    bidders = models.ManyToManyField(Bidder,related_name="bidders",blank=True)
    category = models.ForeignKey(Category,on_delete=models.SET_NULL,null=True)
    bid_start_price = models.IntegerField()
    bid_gap =  models.IntegerField(default=0)
    post_time = models.DateTimeField(auto_now=True)
    on_auction = models.BooleanField(default=False)
    bidding_starts = models.DateTimeField(editable=True,blank=True,null=True)
    bidding_ends = models.DateTimeField(editable=True,blank=True,null=True)

    def __str__(self) -> str:
        return self.product_name

class Onsale(models.Model):
    product_name = models.CharField(max_length=200)
    product_description = models.TextField(max_length=1000)
    product_thumbnail = models.ImageField()
    category = models.ForeignKey(Category,on_delete=models.SET_NULL,null=True)
    price = models.IntegerField()
    post_time = models.DateTimeField(auto_now=True)
    
    def __str__(self) -> str:
        return self.product_name

class Bidds(models.Model):
    bid_product = models.ForeignKey(Product,on_delete=models.CASCADE)
    bidder = models.CharField(max_length=100,default="me")
    bid_price = models.IntegerField()
    bid_time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '%s - %s' % (self.bid_product.product_name,self.bidder)

    @property
    def highest_bid(self):
        hb = self.bid_price
        max(hb)
        return hb



class Product_img(models.Model):
    images = models.ImageField()
    product_id = models.ForeignKey(Product,on_delete=models.CASCADE)

    def __str__(self):
        return self.product_id.product_name


class Contact(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField()
    message = models.TextField()

    def __str__(self):
        return self.email    

auction/forms.py
from django import forms
from.models import Bidds,Contact
from django.contrib.auth.forms import UserCreationForm
from.models import User


class Bidform(forms.ModelForm):
    class Meta:
        model = Bidds
        fields = ('bid_price',)
        widgets = {
            'bid_price':forms.TextInput(attrs={'class':'form-control'}),
        }

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'


class LoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class":"form-control"
            }
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "class":"form-control"
            }
        )
    )

    class Meta:
        model = User
        fields =  ( 'email','password1',)

auction/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.db.models import Avg, Max, Min, Sum
from django.core.paginator import Paginator , EmptyPage ,PageNotAnInteger
from django.contrib.auth.decorators import login_required
from.forms import LoginForm
from django.contrib.auth import authenticate,login,logout
from.models import *
from.forms import Bidform
from django.contrib import messages
from django.db.models import Q
from datetime import datetime
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
from.forms import LoginForm



# Create your views here.
def home(request):
    on_auction =  Product.objects.filter(on_auction=True)
    on_sale =  Product.objects.filter(on_auction=False)
    category =  Category.objects.all()
    bidders   =  Bidds.objects.all()
    product_count  =  Product.objects.filter(on_auction=True).count()
    context = {
        "bid":on_auction,
        "category":category,
        "product_count":product_count,
        "bidders":bidders,
        "on_sale":on_sale,
    
    }
    return render(request,'index.html',context)


def about(request):
    return render (request,'about.html')



def bidders(request):

    bidders = Bidder.objects.all()

    context =  {
        'bidders':bidders
    }

    return render(request,'bidders.html',context)


def faqs(request):
    return render(request,'faqs.html')


def tsandcs(request):
    return render(request, 'tsandcs.html')


def contact(request):
    if request.method == "POST":
        contact = Contact()
        name = request.POST.get('name')
        email = request.POST.get('email')
        message = request.POST.get('message')

        contact.name = name
        contact.email = email
        contact.message = message
        contact.save()
        messages.success(request, 'Your message has been sent we will contact you as ppossible')
        
    return render(request, 'contact.html')
        


def login_process(request):
    form = LoginForm(request.POST or None)
    msg = None
    if request.method == 'POST':
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user=authenticate(request=request,username=username,password=password)  
            if user is not None:
                login(request=request,user=user)
                messages.success(request,f"You have successfuly logged in as {username} ")
                return redirect('home')
                
            else:
                msg = 'invalid credentials'
        else:
            msg = "error invalid creadentials"
    return render(request,'login.html',{'form':form, 'msg':msg})



def bidnow(request):
  
    return render(request,'bidnow.html')


def onsale(request):
   

    return render(request,'on_sale.html')


def product(request,id ):
    product = Product.objects.get(id=id)
    productImage = Product_img.objects.all()
    number_of_bids = Bidds.objects.filter(bid_product=product).count()
    bidds =  product.bidds_set.all().order_by('bid_time')
    highest_bid = Bidds.objects.filter(bid_product=product).aggregate(Max('bid_price'))
    lowest_bid = Bidds.objects.filter(bid_product=product).aggregate(Min('bid_price'))
    

    context = {
		'product': product,
        'number_of_bids':number_of_bids,
        'product_img':productImage ,
        'bidds':bidds,
        'highest_bid': highest_bid ,
        'lowest_bid':lowest_bid,
        
	}
    return render(request, "product_detail.html",context)


@login_required(login_url="login")
def make_bid(request,id):
    product = Product.objects.get(id=id)
    number_of_bids = Bidds.objects.filter(bid_product=product).count()
    highest_bid = Bidds.objects.filter(bid_product=product).aggregate(Max('bid_price'))
    
    g = highest_bid["bid_price__max"]
    print(g)

    form = Bidform(instance=product)

    if request.method == "POST":
        form = Bidform(request.POST,instance=product)
        if form.is_valid():
            bidder = request.user.username
            bid = form.cleaned_data['bid_price']
            b = Bidds(bid_product=product,bidder = bidder, bid_price=bid,bid_time=datetime.now())
            if number_of_bids ==  0:
                if int(bid)  < int(product.bid_start_price)+int(product.bid_gap):
                    messages.error(request, f"You bid hast to be higher than the { product.bid_start_price + product.bid_gap }.")
                    return redirect("make_bid", product.id)
                else:
                    b.save()
                    messages.success(request,f"A bid of USD { bid }.00 for  {product.id} was successfuly")
                    return redirect ('product', id=product.id)


            elif number_of_bids >= 1:
                if int(bid)  < int(g)+int(product.bid_gap):
                    messages.error(request, f"Your bid hast to be higher than the current highest bid { g + product.bid_gap }.")
                    return redirect("make_bid", product.id)

                elif int(bid)  >= int(g)+int(product.bid_gap):
                    b.save()
                    messages.success(request,f"A bid of USD { bid }.00 for  {product.id} was successfuly")
                    return redirect ('product', id=product.id)
    
        else:
            print("form is not Valid")

    else:
        form = Bidform()
    context = {
        'form':form,
        
    }
    return render (request,"add_bid.html",context)



def logout_process(request):
    logout(request)
    messages.success(request,"Logout Successfully")
    return render(request,'index.html')

auction/templates/about.html
{% extends 'base.html' %} 
 {% load static %}

  {% block content %}
  <div class="container">
    <p style="text-align: center; font-size: 30px; font-weight: bold; padding-top: 30px;">ABOUT US</p>
    <form method="POST">
  <div class="about-section">
    <h1>About Us Page</h1>
    <p>Some text about who we are and what we do.</p>
    <p>Resize the browser window to see that this page is responsive by the way.</p>
  </div>
  
  <h2 style="text-align:center">Our Team</h2>
  <div class="row">
    <div class="column">
      <div class="card">
        <img src="/w3images/team1.jpg" alt="Jane" style="width:100%">
        <div class="container">
          <h2>Jane Doe</h2>
          <p class="title">CEO & Founder</p>
          <p>Some text that describes me lorem ipsum ipsum lorem.</p>
          <p>jane@example.com</p>
          <p><button class="button">Contact</button></p>
        </div>
      </div>
    </div>
  
    <div class="column">
      <div class="card">
        <img src="/w3images/team2.jpg" alt="Mike" style="width:100%">
        <div class="container">
          <h2>Mike Ross</h2>
          <p class="title">Art Director</p>
          <p>Some text that describes me lorem ipsum ipsum lorem.</p>
          <p>mike@example.com</p>
          <p><button class="button">Contact</button></p>
        </div>
      </div>
    </div>
  
    <div class="column">
      <div class="card">
        <img src="/w3images/team3.jpg" alt="John" style="width:100%">
        <div class="container">
          <h2>John Doe</h2>
          <p class="title">Designer</p>
          <p>Some text that describes me lorem ipsum ipsum lorem.</p>
          <p>john@example.com</p>
          <p><button class="button">Contact</button></p>
        </div>
      </div>
    </div>
  </div>
</div>


{% endblock %}

auction/templates/add_bid.html
{% extends 'base.html' %} 
 {% load static %}

  {% block content %} 


  <div class="container">
    <div class="row">
      <div class="col col-md-6 mx-auto mt-5 col-md-justyfy-content-center">
        <div class="card card-body bg-success" >
        <div class="card-title text-center text-white">
        <div class="text-capitalize">Make your Bid now</div>
        <form action="" method="post" >
        {%  csrf_token %}
       <div class="input-group my-3">
        <div class="input-group-prepend">
          <span class="input-group-text">USD</span>
        </div>
          <div class="form-control">{{ form }}</div>

        
         <input class="btn btn-primary  mt-2" type="submit" name="submit">

      </div>
    </form>   
  </div>
</div>
</div>
</div>
</div>
</div> 


  {% endblock %}




  

auction/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/3.2.0/css/adminlte.min.css" integrity="sha512-IuO+tczf4J43RzbCMEFggCWW5JuX78IrCJRFFBoQEXNvGI6gkUw4OjuwMidiS4Lm9Q2lILzpJwZuMWuSEeT9UQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/3.2.0/css/alt/adminlte.components.min.css" integrity="sha512-C6GDY2X+A6W2CYRoEykmm+Ta04hV2TqOSer0LJ+TeZCY3+b9i9pDnbwNgvlrpZSZIgBonixchcyVe7Nu8ccauQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/3.2.0/css/alt/adminlte.core.min.css" integrity="sha512-xihZdz1B0BgSS+aKKZn3WCVokTH1I/KbsubJJ/jfk9ir22aAtbFHw+oGPvKJUX76Wtl3kKhO+Wkj6Z47Pa76VQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/3.2.0/css/alt/adminlte.extra-components.min.css" integrity="sha512-Rho/nal+5pKgEFMfnMeJ5iynqFe2y/ev+KwrKIzFALivzIkj+3ymOWzhY/T9m5v9pkDUxZevORjoavsYCVbU/w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/3.2.0/css/alt/adminlte.light.min.css" integrity="sha512-sH43x9hDH6VYZCimbGd58vYrO4uMdmPn3m8QUgxNYi4MNmj4sbt+fN1jG+TnVA2Q0SA6tvEo6W6P1Z0FA+6AXA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/3.2.0/css/alt/adminlte.pages.min.css" integrity="sha512-G5uca2T4CI7/9IHrOI1DKXQaqBN17tyNzgL4rMSEavhnKwN82WDWptayW8/VbzI21UCjpErfXv7jRve+iCbb9g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  
  
  <link rel="stylesheet" href="{% static 'style.css' %}">
  
  <!-- overlayScrollbars -->
 
</head>
  <title>Welcome To Bg Auctions</title>
</head>
<body>
  <div class="container">
    <div class="container">
      <div class="row row-cols-lg-3 upper-nav justi">
        <div class="col-5 mt-2">
          <h5 class="header mt-2 text-white ">Bg Auctions</h5>
        </div>
        <div class="col-6 ">
          <h5 class=" mt-2 ">Bidding Stats here! </h5>
          
        </div>
        <div class="col-3 mt-2">
          <h5 class="text-right text-light">Call--07785534526 </h5>
        </div>
      </div>
    </div>
    <section class="lower-nav">
      <nav class="navbar navbar-expand-md bg-danger ">
      <div class="container">
        <div class="row">
          <div class="col">
          <button class="navbar-toggler" data-bs-toggle="collapse"  data-bs-target="#nav" aria-controls="nav" aria-label="Expand Navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
         <div class="collapse navbar-collapse" id="nav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a href="{%  url 'home' %}" class="nav-link text-white">Home</a>
          </li>

          <li class="nav-item dropdown">
            <a id="dropdownSubMenu1" href="{%  url 'bidnow' %}" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="nav-link dropdown-toggle nav-link text-white">On Auction</a>
            <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow">
              <li><a href="{% url 'bidnow' %}" class="dropdown-item">All categories </a></li> 
              {%  for c in category %}
              <li><a href="{% url 'bidnow' %}?q={{ c.name }}" class="dropdown-item">{{ c.name }} </a></li>
              {% endfor %}

            
              <!-- End Level two -->
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a id="dropdownSubMenu1" href="{%  url 'onsale' %}" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="nav-link dropdown-toggle nav-link text-white">On Sale</a>
            <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow"> 
              <li><a href="{% url 'onsale' %}" class="dropdown-item">All categories </a></li> 
              {%  for c in category %}
              <li><a href="{% url 'onsale' %}?q={{ c.name }}" class="dropdown-item">{{ c.name }} </a></li>
              {% endfor %}

            
              <!-- End Level two -->
            </ul>
          </li>
          <li class="nav-item">
            <a href="{%  url 'about' %}" class="nav-link text-white">About</a>
          </li>
          <li class="nav-item">
            <a href="{%  url 'tsandcs' %}" class="nav-link text-white">TsAndCs</a>
          </li>
          <li class="nav-item">
            <a href="{%  url 'contact' %}" class="nav-link text-white">Contact</a>
          </li>
       
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a href="{% url 'logout' %}" class="nav-link text-white">Logout</a>
          </li>
          {%  else %}
          <li class="nav-item">
            <a href="{%  url 'login' %}" class="nav-link text-white">Login</a>
          </li>
          
        {% endif %}
        
        </ul>
        <div class="d-flex " >
        <form method"POST" class="d-flex " role="search">
          <input class="form-control me-2" name"q" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-primary" type="submit">Search</button>
        </form>
      </div>
      </div>
    </div>
    </div>
      </div>
    </nav>
    </section>
    {% if messages %}
    {% for message in messages  %}
    {% if message.tags == "success" %}
    <div class="alert alert-success">
      {{message}}
    </div>
    {% endif %}
    {% if message.tags == "error" %}
    <div class="alert alert-danger">
      {{ message}}
    </div>
    {% endif %}
        {% endfor %}
        {% endif %}
 
  

  {%  block content %}


  {%  endblock %}

  <section class="">
    <div class="container text-center text-md-start mt-5">
      <!-- Grid row -->
      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
          <!-- Content -->
          <h6 class="text-uppercase fw-bold mb-4">
            <i class="fas fa-gem me-3 text-secondary"></i>BG Auctions
          </h6>
          <p>
            BG Auctions offers a hassle free service, beginning with effective advertising and ending with promp
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Quick links
          </h6>
          <p>
            <a href="#!" class="text-reset">About</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Terms</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Contact</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Home</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Useful links
          </h6>
          <p>
            <a href="{% url "faqs" %}" class="text-reset">FAQ</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Terms</a>
          </p>
          
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
          <p><i class="fas fa-home me-3 text-secondary"></i>Mutare rd GMB turn Off After N. Richards Msasa, Harare, Zimbabwe</p>
          <p>
            <i class="fas fa-envelope me-3 text-secondary"></i>
            ekawenya@gmail.com
          </p>
          <p><i class="fas fa-phone me-3 text-secondary"></i> + 263 71 250 1759</p>
          <p><i class="fas fa-print me-3 text-secondary"></i> + 263 77 235 7278</p>
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->
    </div>
  </section>
  <!-- Section: Links  -->

  <!-- Copyright -->
  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.025);">
    © 2023 Copyright:
    <a class="text-reset fw-bold" href="">AG AUCTIONS</a>
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->
    </section>
  </section>   


<script src="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/3.2.0/js/adminlte.min.js" integrity="sha512-KBeR1NhClUySj9xBB0+KRqYLPkM6VvXiiWaSz/8LCQNdRpUm38SWUrj0ccNDNSkwCD9qPA4KobLliG26yPppJA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/3.2.0/js/demo.min.js" integrity="sha512-1WYc267IxoxmWXSOf4gXEEiyfgK041c8LYQQBnIl4EsvcR5T+x+nJ2f783U29u2QX7OzDTYI0nEyTZ05O8Y1jg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/3.2.0/js/pages/dashboard.min.js" integrity="sha512-wXkHJ2i8Z5fK/q6k7qe38qA6uD+VpLC/LL2XobX3rVVw6F3//fDWwoqMQ2Mgy5nf9BIvW2gLbILQJTIO/gDrDg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/3.2.0/js/pages/dashboard3.min.js" integrity="sha512-l8RWdqTMUrIWPpdL2yB14+n+2WBPFe/KhH65aa3YAi+fRVvRMKxMVgmdk0/EUXLRKLFJmUH4rBABfxBsribrJg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/3.2.0/js/pages/dashboard2.min.js" integrity="sha512-/On5eFU1vz1sGgejVpebEmg91zdKYXBcm4HPzDHcKOF1icilwxSR0C1ClBcK9IodnQdow2HjmHnqxt8PdQRrAA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script type="text/javascript">

  let thumbnails = document.getElementsByClassName ('thumbnail')
  let activeImages = document.getElementsByClassName ('active')

  for (var i=0; i <thumbnails.length; i++){

    thumbnails[i].addEventListener('mouseover',  function(){
      

      if (activeImages.length > 0){
         activeImages[0].classList.remove('active')
      }

      this.classList.add('active')
      document.getElementById('product-zoom1').src = this.src
    })

  }

</script>
</body>
</html>

auction/templates/pd_detail.html
{% extends 'base.html' %} 
{% load static %}

 {% block content %}
 <div class="container mt-5 mb-5">
    <div class="row d-flex justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="row">
                    <a  class="btn btn-primary" href="{{ request.META.HTTP_REFERER  }}"> Go Back</a>
                    <div class="col-lg-5 pb-5">
                      <div id="product-carousel" class="carousel slide" data-ride="carousel">
                          <div class="carousel-inner border">
                              <div class="carousel-item active">
                                  <img class="w-100 h-100" src="{{ product.product_thumbnail.url }}">
                              </div>
                              {% for pi in product.product_img_set.all %}
                              <div class="carousel-item">
                                  <img class="w-100 h-100" src="{{ pi.images.url }}" alt="Image">
                              </div>
                              {%  endfor %}
                              
                          </div>
                          <a class="carousel-control-prev" href="#product-carousel" data-slide="prev">
                              <i class="fa fa-2x fa-angle-left text-dark"></i>
                          </a>
                          <a class="carousel-control-next" href="#product-carousel" data-slide="next">
                              <i class="fa fa-2x fa-angle-right text-dark"></i>
                          </a>
                      </div>
                  </div>
      
                    <div class="col-md-6">
                        <div style="margin:10px;">
                            <h6><strong>{{ product.product_name}}</strong></h6>
                           
                            <p class='warning'><small>{{ product.product_description  }}</small></p>
                            <br>
                            <hr>
                            <h6><strong> <span class='text-danger'>
                             
                              
                              {% if product.bidding_starts < 1 %} 
                              <div class="info-box mb-3 bg-warning p-2">
                                <span class="info-box-icon"></span>
                                <div class="info-box-content">
                                  <span class="info-box-text">Bidding starts in </span>
                                  <span class="info-box-number ">{{ product.bidding_starts|timeuntil }}</span>
                                </div>
                                <!-- /.info-box-content -->
                              </div>
                            


                              {% endif %}
                            

                             </span> </strong></h6>
                           
                              <div class="info-box mb-3 bg-success p-2">
                                <span class="info-box-icon"></span>
                  
                                <div class="info-box-content">
                                  <span class="info-box-text">Starting price   </span>
                                  <span class="info-box-number ">USD {{  product.bid_start_price|floatformat:2   }}</span>
                                </div>
                                <!-- /.info-box-content -->
                              </div>
                            
                         
                              <div class="info-box mb-3 bg-danger p-2">
                                <span class="info-box-icon"></span>
                  
                                <div class="info-box-content">
                                  <span class="info-box-text">Highest Bid   </span>
                                  <span class="info-box-number ">USD {{ highest_bid.bid_price__max|floatformat:2   }}</span>
                                </div>
                                <!-- /.info-box-content -->
                              </div>
                              
                            
                              <div class="info-box mb-3 bg-warning p-2">
                                <span class="info-box-icon"></span>
                  
                                <div class="info-box-content">
                                  <span class="info-box-text">Lowest Bid   </span>
                                  <span class="info-box-number ">USD {{ lowest_bid.bid_price__min|floatformat:2   }}</span>
                                </div>
                                <!-- /.info-box-content -->
                              </div>
                            
                            <br>
                            <hr>
          
                           
                          
                            <br>
                            <hr>
                            <div class="col-md-12">
                              <!-- DIRECT CHAT -->
                              Active Bids
                                <!-- /.card-header -->
                                <div class="card-body">
                                  <!-- Conversations are loaded here -->
                                  <div class="direct-chat-messages">
                                    <!-- Message. Default to the left -->
                                     {% if not product.bidds_set.all %}
                                    <p>There are no bids yet </p>
                                    {%  else %}
                                     {% for bid in bidds %}
                                    <div class="direct-chat-msg">
                                      <div class="direct-chat-infos clearfix">
                                        <span class="direct-chat-name float-left">{{ bid.bidder}}</span>
                                        <span class="direct-chat-timestamp float-right">{{ bid.bid_time|timesince }}</span>
                                      </div>
                                      <!-- /.direct-chat-infos -->
                                      <img class="direct-chat-img" src="{% static 'dist/img/user1-128x128.jpg' %}" alt="message user image">
                                      <!-- /.direct-chat-img -->
                                      <div class="direct-chat-text">
                                       
                                        <span class="badge badge-warning "> USD {{ bid.bid_price|floatformat:2  }}</span></a>
                                      </div>
                                      <!-- /.direct-chat-text -->
                                    </div>
                                
                                    {% endfor %}
                                    {%  endif %}
              
                                  </div>
                                  <!--/.direct-chat-messages-->
              
                                 
                                <!-- /.card-footer-->
                              </div>
                              <!--/.direct-chat -->
                            >
                  
                    </div>
                    {%  if user.is_authenticated %}
                    <p><a  class="btn btn-primary ml-3" href="{% url "make_bid" product.pk %}"> Bid Now</a></p> 
                    {% else %}
                    <p><a  class="btn btn-danger" href="{% url 'login' %}"> login to Bid</a></p> 
                    {% endif %}
                </div>
                
            </div>
        </div>
    </div>
</div>

  {% endblock %}